version: "3.8"

services:
  # MySQL Service
  mysql:
    image: mysql:8.0
    container_name: ecommerce-mysql
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  # PHP Service
  php:
    build:
      context: .
      target: php
    container_name: ecommerce-php
    environment:
      - CONTAINER_ROLE=app
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - mysql

  # phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: ecommerce-phpmyadmin
    ports:
      - "9000:80"
    environment:
      - PMA_HOST=${DB_HOST}
      - PMA_PORT=${DB_PORT}
      - PMA_ARBITRARY=1
    depends_on:
      - mysql
      - php
volumes:
  db-data:
    name: ecommerce-mysql




